Repository AY2223S2-CS2103T-T11-3/tp, pull requests merged in 2023-03, with the labels that each got.

#52 Update CI status badge to reflect correct repo
  README.md
Labels: type.Bug

#98 Fix bug for not saving contacts after marking
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
Labels: type.Bug

#130 Enable assertion for gradle
  build.gradle
Labels: type.Task, priority.High

#127 Update UserGuide to reflect structures better
  docs/UserGuide.md
  docs/images/Logo.png
Labels: type.Task

#129 Modify reminder code
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/EventBookParser.java
  src/main/java/seedu/address/logic/parser/RemindCommandParser.java
  src/main/java/seedu/address/model/event/StartTimeWithinDaysPredicate.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
  src/test/java/seedu/address/logic/parser/EventBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemindCommandParserTest.java
  src/test/java/seedu/address/model/event/StartTimeWithinDaysPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalTimes.java
Labels: type.Bug

#135 Update app version to v1.2.1
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, priority.High

#138 Update PPP to reflect items done
  docs/team/extrashotlatte.md
Labels: type.Task

#137 Update DG
  docs/DeveloperGuide.md
Labels: type.Task

#142 Update default placeholder data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Story, severity.VeryLow

#143 Fix a few typos in UG
  docs/UserGuide.md
Labels: type.Bug, severity.Medium

#145 Bug Fix
  docs/images/Ui.png
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug

#128 Modification in implementation
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/contact/ContactPhone.java
  src/test/data/JsonSerializableContactListTest/typicalEventsContactList.json
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/contact/ContactPhoneTest.java
  src/test/java/seedu/address/model/contact/ContactTest.java
  src/test/java/seedu/address/testutil/TypicalContacts.java
Labels: type.Bug

#146 Update DG
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ContactClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EventClassDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/ComponentManagers.png
  docs/images/ContactClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EventClassDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/images/style.png
Labels: type.Task, priority.High

#149 Update PPP
  docs/team/glozxi.md
Labels: type.Task, priority.Medium

#150 Correct some error spotted
  docs/DeveloperGuide.md
Labels: type.Bug

#151 Update UG to include more commands
  docs/UserGuide.md
Labels: type.Task, priority.High

#165 Update UG
  docs/UserGuide.md
  docs/images/Callout_UI.png
Labels: type.Task

#170 Update UML of DG for linkcontact
  docs/DeveloperGuide.md
  docs/diagrams/LinkContactActivityDiagram.puml
  docs/images/LinkContactActivityDiagram.png
Labels: type.Task

#160 Update DG and remove rate command
  docs/DeveloperGuide.md
  docs/diagrams/UnmarkActivityDiagram.puml
  docs/images/UnmarkActivityDiagram.png
  src/main/java/seedu/event/logic/commands/RateCommand.java
  src/main/java/seedu/event/logic/parser/EventBookParser.java
  src/main/java/seedu/event/logic/parser/RateCommandParser.java
  src/test/java/seedu/event/logic/commands/RateCommandTest.java
  src/test/java/seedu/event/logic/parser/EventBookParserTest.java
  src/test/java/seedu/event/logic/parser/RateCommandParserTest.java
Labels: type.Task

#172 Change address book to event book
  src/main/java/seedu/event/MainApp.java
  src/main/java/seedu/event/logic/Logic.java
  src/main/java/seedu/event/logic/commands/AddCommand.java
  src/main/java/seedu/event/logic/commands/ClearCommand.java
  src/main/java/seedu/event/logic/commands/DeleteCommand.java
  src/main/java/seedu/event/logic/commands/EditCommand.java
  src/main/java/seedu/event/logic/commands/ListCommand.java
  src/main/java/seedu/event/logic/commands/MarkCommand.java
  src/main/java/seedu/event/logic/commands/UnmarkCommand.java
  src/main/java/seedu/event/model/EventBook.java
  src/main/java/seedu/event/model/ModelManager.java
  src/main/java/seedu/event/model/ReadOnlyEventBook.java
  src/main/java/seedu/event/model/event/Address.java
  src/main/java/seedu/event/model/event/Email.java
  src/main/java/seedu/event/model/event/Event.java
  src/main/java/seedu/event/model/event/Name.java
  src/main/java/seedu/event/model/event/Rate.java
  src/main/java/seedu/event/model/tag/Tag.java
  src/main/java/seedu/event/storage/JsonSerializableEventBook.java
  src/test/java/seedu/event/logic/commands/CommandTestUtil.java
  src/test/java/seedu/event/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/event/logic/commands/EditCommandTest.java
  src/test/java/seedu/event/logic/commands/MarkCommandTest.java
  src/test/java/seedu/event/logic/commands/UnmarkCommandTest.java
Labels: priority.High

#173 Update UG
  docs/UserGuide.md
Labels: priority.High
